api/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path("view/", views.postOverview, name='api-overview'),
    path("post/post-list/", views.postList, name='list-view'),
    path("post/post-detail/<int:pk>", views.postDetail, name='list-detail'),
    path("post/post-create/", views.createPost, name='create-post'),
    path("post/post-update/<int:pk>/", views.updatePost, name='update-post'),
    path("post/post-delete/<int:pk>/", views.deletePost, name='delete-post'),
    
]

feed/urls.py
from django.urls import path
from . import views


app_name = 'feed'


urlpatterns = [
     path("", views.homepage, name='index'),
     path("post_detail/<int:id>/<slug:slug>/", views.post_detail, name='post_detail'),
  
    
]

myport/urls.py
from django.urls import path 
from . import views


app_name = 'myport'

urlpatterns = [
   
    path("about/", views.about, name='about'),
    path("contact/", views.contact, name='contact'),
    path("tutorial/", views.tutorial, name='tutorial'),
    path("portfolio", views.portfolio_list, name='portfolio'),
    path("<slug:category_slug>/", views.portfolio_list, name='project_list_by_category'),
    path("portfolio/<int:id>/<slug:slug>/", views.portfolio_detail, name='project_detail'),
    path("portfolio", views.portfolio_list, name='portfolio'),
    path("<slug:category_slug>/", views.portfolio_list, name='project_list_by_category'),
    path("portfolio/<int:id>/<slug:slug>/", views.portfolio_detail, name='project_detail'),    
]

myportfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("myport.urls", namespace='myport')),
    path('', include("feed.urls", namespace='feed')),
    path('api/', include("api.urls")),
    path('portapi/', include("portapi.urls")),
    path('dashboard/', include("dash.urls", namespace='dash')),
    path('tutorials/', include("tutorial.urls", namespace='tutorial')),
    path('__debug__/', include("debug_toolbar.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tutorial/urls.py
from django.urls import path
from . import views


app_name = 'tutorial'


urlpatterns = [
    path('tutorial/', views.course_list, name='courses'),
    path('tutorial/<slug:category_slug>/', views.course_list, name='course_list_by_category'),
     path("portfolio/<int:id>/<slug:slug>/", views.course_detail, name='course_detail'),
    
]

myport/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name'])
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
    def __str__(self):
            return self.name
        
    def get_absolute_url(self):
        return reverse('myport:project_list_by_category', args=[self.slug])
    
        
class Project(models.Model):
    category = models.ForeignKey(Category,  related_name='projects', on_delete=models.CASCADE)
    title = models.CharField(max_length=240)
    description = models.TextField()
    slug = models.SlugField(max_length=240)
    image = models.ImageField(upload_to='projects/images', blank=True)
    image_url = models.URLField(max_length=500, blank=True)
    embed_code = models.CharField(max_length=550, blank=True)

    git_source_code = models.CharField(max_length=300, blank=True)

    website_url = models.URLField(max_length=500, blank=True)
    github = models.URLField(max_length=500, blank=True)

    date = models.DateField(auto_now=True)
    
    class Meta:
        ordering = ['title']
        indexes = [
            models.Index(fields=['id', 'slug']), 
            models.Index(fields=['title']), 
            models.Index(fields=['-date']), 
            
        ]
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('myport:project_detail', args=[self.id, self.slug])
    

    

       
    
 

myport/forms.py
from django import forms



class EmailContactForm(forms.Form):
    full_name = forms.CharField(max_length=30)
    email = forms.EmailField()
    subject = forms.CharField(max_length=150)
    comments = forms.CharField(required=False, widget=forms.Textarea)
    comments = forms.CharField(required=False, widget=forms.Textarea)
    
    

myport/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from .models import Category, Project
from django.contrib.auth.models import User
from django.core.mail import send_mail
from .forms import EmailContactForm

# Create your views here.



    
def about(request):
    name = 'Peter Omoruyi'
    return render(request, 'myport/portfolio/about.html', {
        'name': name,
    })
    
def contact(request):
    
    sent = False
    if request.method == 'POST':
        # submit the form 
        form = EmailContactForm(request.POST)
        if form.is_valid():
            # form pass validation
            cd = form.cleaned_data
            subject = f"{cd['subject']} " 
            sender_email = f"{cd['email']} " 
            message = f"{cd['full_name']} \'s comments: {cd['comments']}"
            send_mail(subject, message, 'mindhealth14@hotmail.com', ['mindhealth14@gmail.com', sender_email] )
            sent = True
            
    else:
        form = EmailContactForm()
        
    return render(request, 'myport/portfolio/contact.html', {
        'form': form,
        'sent': sent
    })
    
    
    
    
    
    
    return render(request, 'myport/project/contact.html', {
        'hello': hello, 
    })
    

def tutorial(request):
    message = 'We are coming soon'
    return render(request, 'myport/portfolio/tutorial.html', {
        'message': message, 
    })

def portfolio_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    projects = Project.objects.all()
   
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        projects  = projects.filter(category=category)
        
    return render(request, 'myport/portfolio/portfolio.html', {
        'category': category,
        'categories': categories,
        'projects': projects,
        
    })
    
    
def portfolio_detail(request, id, slug):
    portfolio = get_object_or_404(Project, id=id, slug=slug)
    return render(request, 'myport/portfolio/detail.html', {
        'portfolio': portfolio
    })
    

def map_view(request):
    return render(request, 'map_template.html')



def load_more_data(request):
    offset = int(request.GET.get('offset', 0))
    limit = 10  # Set your desired limit for each batch of data
    data = Project.objects.all()[offset:offset+limit]
    # Render a template with the fetched data
    return render(request, 'portfolio.html', {'data': data})

    
    

myport/templates/myport/base.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
     integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
      integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
     

     <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>

    <title>
    {% block title %}
        Home Page
    {% endblock title %}
        </title>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <nav class="navbar navbar-expand-lg bg-nav">
                <div class="container-fluid">
                  <a class="navbar-brand logos" href="{% url 'feed:index' %}">EtinTech</a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'feed:index' %}">Home</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'myport:about' %}">About</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'myport:portfolio' %}">Portfolio</a>
                      </li>
                      <li class="nav-item">
<<<<<<< HEAD
                        <a class="nav-link" href="{% url 'myport:tutorial' %}">Tutorial</a>
=======
                        <a class="nav-link" href="{% url 'tutorial:courses' %}">Tutorial</a>
>>>>>>> 2619a3918320ef852ef3d49de35081a6e110ccb9
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'myport:contact' %}">Contact</a>
                      </li>
                      
                    </ul>
                  </div>
                </div>
              </nav>
        </div>

        <div class="row my-border">
          
          <div class="col-md-10">
           <span>
            <nav class="navbar bg-search">
              <div class="container-fluid">
                <form class="d-flex" role="search" style="width: 65%;">
                   <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                   <button class="btn btn-color" type="submit">Search</button>
                </form>
              </div>
           </nav>
           </span>


        </div>

          
          {% if request.user.is_authenticated %}
          <div class="col-md-2"><p class="mt-2"><a href="{% url 'logout' %}">Logout</a></p></div>
          {% else %}
          <div class="col-md-2"><p class="mt-2" id="login-modal">Login</p></div>
          {% endif %}
        </div>
    </div>

<<<<<<< HEAD
    <div class="container main"> 
=======
    <div class="container-fluid main"> 
>>>>>>> 2619a3918320ef852ef3d49de35081a6e110ccb9
      {% block content %}        {% endblock content %}
    </div>



<<<<<<< HEAD

      <hr class="mt-5"> 
      <br>



=======
      <hr class="mt-3"> 
      <br>

>>>>>>> 2619a3918320ef852ef3d49de35081a6e110ccb9
     <!-- Footer -->
<footer class="btn-color text-center">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>

      <!-- Github -->
      <a data-mdb-ripple-init class="btn btn-outline btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->

    <!-- Section: Form -->
    <section class="">
      <form action="">
        <!--Grid row-->
        <div class="row d-flex justify-content-center">
          <!--Grid column-->
          <div class="col-auto">
            <p class="pt-2">
              <strong>Sign up for our newsletter</strong>
            </p>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-5 col-12">
            <!-- Email input -->
            <div data-mdb-input-init class="form-outline mb-4">
              <input type="email" id="form5Example24" class="form-control" />
              <label class="form-label" for="form5Example24">Email address</label>
            </div>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-auto">
            <!-- Submit button -->
<<<<<<< HEAD
            <button data-mdb-ripple-init type="submit" class="btn btn-outline mb-4">
=======
            <button data-mdb-ripple-init type="submit" class="btn btn-color mb-4" style="border: 2px solid rgb(222, 222, 222);">
>>>>>>> 2619a3918320ef852ef3d49de35081a6e110ccb9
              Subscribe
            </button>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </form>
    </section>
    <!-- Section: Form -->

    <!-- Section: Text -->
    <section class="mb-4">
<<<<<<< HEAD
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt distinctio earum
        repellat quaerat voluptatibus placeat nam, commodi optio pariatur est quia magnam eum
        harum corrupti dicta, aliquam sequi voluptate quas.
      </p>
=======
      <h2>Let's talk</h2>
      <p>Looking for a full-stack engineer who can develop your idea?</p>
      
      <p> Wanna get in touch or talk about a project? I'm currently available for the next project. Feel free to contact me via email at
         peter@etintech.com.au or drop a line in the form at the contact page. </p>
>>>>>>> 2619a3918320ef852ef3d49de35081a6e110ccb9
    </section>
    <!-- Section: Text -->

    <!-- Section: Links -->
    <section class="">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
<<<<<<< HEAD
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a class="text-body" href="#!">Link 1</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 2</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 3</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 4</a>
=======
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0 text-left">
          <h5 class="text-uppercase">Home</h5>

          <ul class="list-unstyled mb-0 text-left">
            <li>
              <a class="text-body" href="http://172.105.190.111:8000/">Home</a>
            </li>
            <li>
              <a class="text-body" href="/about/">About Us</a>
            </li>
            <li>
              <a class="text-body" href="/portfolio/">Porfolio</a>
            </li>
            <li>
              <a class="text-body" href="/contact">Contact</a>
>>>>>>> 2619a3918320ef852ef3d49de35081a6e110ccb9
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
<<<<<<< HEAD
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a class="text-body" href="#!">Link 1</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 2</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 3</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 4</a>
=======
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0 text-left">
          <h5 class="text-uppercase">About</h5>

          <ul class="list-unstyled mb-0 text-left">
            <li>
              <a class="text-body" href="#!">Etintech</a>
            </li>
            <li>
              <a class="text-body" href="/about/">Peter O</a>
            </li>
            <li>
              <a class="text-body" href="#!">Philosophy </a>
            </li>
            <li>
              <a class="text-body" href="#!">Passions</a>
>>>>>>> 2619a3918320ef852ef3d49de35081a6e110ccb9
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
<<<<<<< HEAD
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a class="text-body" href="#!">Link 1</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 2</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 3</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 4</a>
=======
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0 text-left">
          <h5 class="text-uppercase">Portfolio</h5>

          <ul class="list-unstyled mb-0text-left">
            <li>
              <a class="text-body" href="/portfolio/">Portfolio</a>
            </li>
            <li>
              <a class="text-body" href="/havard-university-projects/">Harvard Projects</a>
            </li>
            <li>
              <a class="text-body" href="/udemy-projects/">Udemy Project</a>
            </li>
            <li>
              <a class="text-body" href="/old-projects/">Old Projects</a>
>>>>>>> 2619a3918320ef852ef3d49de35081a6e110ccb9
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
<<<<<<< HEAD
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a class="text-body" href="#!">Link 1</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 2</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 3</a>
            </li>
            <li>
              <a class="text-body" href="#!">Link 4</a>
=======
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0 text-left">
          <h5 class="text-uppercase">Contacts Us</h5>

          <ul class="list-unstyled mb-0 text-left">
            <li>
              <a class="text-body" href="/contact/">Locations</a>
            </li>
            <li>
              <a class="text-body" href="mailto:peter@etintech.com.au">Emails</a>
            </li>
            <li>
              <a class="text-body" href="/contact/">Contact Form</a>
>>>>>>> 2619a3918320ef852ef3d49de35081a6e110ccb9
            </li>
          </ul>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </section>
    <!-- Section: Links -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2020 Copyright:
<<<<<<< HEAD
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
=======
    <a class="text-reset fw-bold" href="http://172.105.190.111:8000/">etintech.com.au</a>
>>>>>>> 2619a3918320ef852ef3d49de35081a6e110ccb9
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
  

      {% include 'myport/modal.html' %}
      <script text/javascript" src="{% static 'js/script.js' %}" defer></script>
      <script text/javascript" src="{% static 'js/main.js' %}" defer></script>
<<<<<<< HEAD
=======
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8poRx7b30SYsJvA5-_VPlfkdrjpY89nU"></script>

>>>>>>> 2619a3918320ef852ef3d49de35081a6e110ccb9
      
</body>
</html>

myport/templates/myport/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

    <footer style="background-color: rebeccapurple;">
        test
    </footer>
</body>
</html>

myport/templates/myport/modal.html
{% load static %}
<dialog  data-modal id="login-admin-modal">
    <!-- Content of the modal dialog goes here -->
    <div class="d-flex justify-content-md-between" >  <h1 class="flex-grow-1 st" style="margin-left: 3em;">Admin Login </h1><span class="close-modal"> &#x2715;</span></div>
    
    <hr>
    <!-- js-post-text is added to the form class wigdet at form.py -->

   <div class="w-full" id="login-wrapper">
   
    <form  action="{% url 'login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username</label>
      <p><input class="form-control" type="text" id="username" name="username"></p>
      <label for="password">Password</label>
      <p><input class="form-control" type="password" id="password" name="password"></p>
      <p class="d-grid"><button type="submit" class="btn btn-color mt-2">Login</button></p>
    </form>
   </div>
    
</dialog>

<!-- Close button modal here  -->