api/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path("view/", views.postOverview, name='api-overview'),
    path("post/post-list/", views.postList, name='list-view'),
    path("post/post-detail/<int:pk>", views.postDetail, name='list-detail'),
    path("post/post-create/", views.createPost, name='create-post'),
    path("post/post-update/<int:pk>/", views.updatePost, name='update-post'),
    path("post/post-delete/<int:pk>/", views.deletePost, name='delete-post'),
    
]

dash/urls.py
from django.urls import path
from . import views

app_name = 'dash'

urlpatterns = [
   path('dashboard-admin/', views.dashboard, name='dashboard-admin'),
   path('dashboard-admin-portfolio/', views.portfolio_admin, name='dashboard-admin-portfolio')
]

myportfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("myport.urls", namespace='myport')),
    path('', include("feed.urls", namespace='feed')),
    path('api/', include("api.urls")),
    path('portapi/', include("portapi.urls")),
    path('dashboard/', include("dash.urls", namespace='dash')),
    path('tutorials/', include("tutorial.urls", namespace='tutorial')),
    path('__debug__/', include("debug_toolbar.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

dash/models.py
from django.db import models

# Create your models here.

myport/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name'])
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
    def __str__(self):
            return self.name
        
    def get_absolute_url(self):
        return reverse('myport:project_list_by_category', args=[self.slug])
    
        
class Project(models.Model):
    category = models.ForeignKey(Category,  related_name='projects', on_delete=models.CASCADE)
    title = models.CharField(max_length=240)
    description = models.TextField()
    slug = models.SlugField(max_length=240)
    image = models.ImageField(upload_to='projects/images', blank=True)
    image_url = models.URLField(max_length=500, blank=True)
    embed_code = models.CharField(max_length=550, blank=True)

    git_source_code = models.CharField(max_length=300, blank=True)

    website_url = models.URLField(max_length=500, blank=True)
    github = models.URLField(max_length=500, blank=True)

    date = models.DateField(auto_now=True)
    
    class Meta:
        ordering = ['title']
        indexes = [
            models.Index(fields=['id', 'slug']), 
            models.Index(fields=['title']), 
            models.Index(fields=['-date']), 
            
        ]
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('myport:project_detail', args=[self.id, self.slug])
    

    

       
    
 

dash/forms.py
from django import forms
from myport.models import Project

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['category', 'title', 'description', 'slug', 'image', 'image_url', 'embed_code', 'git_source_code']

dash/views.py
from django.shortcuts import render

# Create your views here.

def dashboard(request):
    hello = 'Hello world'
    return render(request, 'dash/index.html', {
        'hello': hello
    })
    
    
def portfolio_admin(request):
    hello = 'Hello world'
    return render(request, 'dash/port-admin.html', {
        'hello': hello
    })

dash/templates/dash/index.html
{% extends 'myport/base.html' %}
{% load static %}


{% block title %}
    
{% endblock title %}




{% block content %}

{% if request.user.is_authenticated %}
<div class="row">
  <div class="col-md-3">
    <p>Logged in user: <b>{{ request.user }}</b></p>
  </div>

  <div class="col-md-9">
    <div class="d-flex flex-row-reverse">
      <div ><p style="padding-right: 35px;"><b>Etintech</b></p></div>
    </div>
  </div>
</div>
<hr>
   <div class="row">
      <div class="col-md-3">

          <div class="card" style="width: 18rem;">
              <div class="card-header">
                Featured
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item"  onclick="openPostModal()">Add Post</li>
                <li class="list-group-item"><a href="{% url 'dash:dashboard-admin-portfolio' %}">View Portfolio </a></li>
              </ul>
            </div>


      </div>
      <div class="col-md-9 px-5">
          
              <div class="list-wrapper">

              </div>
         
      </div>
  
   </div>

   {% include 'dash/modal.html' %}

   {% else %}

   <div class="col-md-6">
    <h1>Login</h1>
    <hr>
    
    <div class="w-full">
   
      <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <p><input class="form-control" type="text" id="username" name="username"></p>
        <label for="password">Password</label>
        <p><input class="form-control" type="password" id="password" name="password"></p>
        <p class="d-grid"><button type="submit" class="btn btn-color mt-2">Login</button></p>
      </form>
     </div>
  
  
  </div>

  <p> This page for authorize users only </p>
  <p> To register for an admin login send an email from the contact form </p>
  <p> <a href="http://localhost:8000/contact/">Click here for contact</a> </p>
   
{% endif %}

{% endblock content %}

    

dash/templates/dash/login.html
{% extends 'myport/base.html' %}
{% load static %}


{% block title %}
    Login Page
{% endblock title %}



{% block content %}

<div class="col-md-6">
    <h1>Login</h1>
    <hr>
    
    <div class="w-full">
   
      <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <p><input class="form-control" type="text" id="username" name="username"></p>
        <label for="password">Password</label>
        <p><input class="form-control" type="password" id="password" name="password"></p>
        <p class="d-grid"><button type="submit" class="btn btn-color mt-2">Login</button></p>
      </form>
     </div>
  
  
  </div>

  <p> This page for authorize users only </p>
  <p> To register for an admin login send an email from the contact form </p>
  <p> <a href="http://localhost:8000/contact/">Click here for contact</a> </p>


{% include 'myport/modal.html' %}
{% endblock content %}
    

dash/templates/dash/modal.html
{% load static %}

<dialog id="post-admin-modal"  data-post-modal>
    <!-- Content of the modal dialog goes here -->
    <div class="d-flex justify-content-md-between" > 
         <h3 class="flex-grow-1 st" style="margin-left: 15px;">Certificate Post </h3><span class="close-post-modal"> &#x2715;</span></div>
    
    <hr>
    <!-- js-post-text is added to the form class wigdet at form.py -->

   <div class="w-full" id="form-wrapper">
   
    <form id="postForm" enctype="multipart/form-data">
      <label for="title">Title:</label>
      <p><input class="form-control" type="text" id="title" name="title"></p>
      <label for="slug">Slug:</label>
      <p><input class="form-control" type="text" id="slug" name="slug"></p>
      <p><textarea id="description" name="description" rows="3" class="form-control"></textarea></p>
      <label for="embed-code">Embed Code:</label>
      <p><input type="text" id="embed_code" name="embed_code" class="form-control" > </p>
      <label for="image">Image</label>
      <p><input class="form-control" type="file" id="image" name="image"></p>
      <p class="d-grid"><button type="submit" class="btn btn-color mt-2">Submit</button></p>
    </form>
   </div>
    
</dialog>

<!-- Close button modal here  -->


<dialog id="port-admin-modal"  data-port-modal>
  <!-- Content of the modal dialog goes here -->
  <div class="d-flex justify-content-md-between" > 
       <h3 class="flex-grow-1 st" style="margin-left:15px">Create New Portfolio & Update </h3><span class="close-port-modal"> &#x2715;</span></div>
  
  <hr>
  <!-- js-post-text is added to the form class wigdet at form.py -->

 <div class="w-full" id="form-wrapper">
 
  <form id="portForm" enctype="multipart/form-data">
    <label for="id_category">Category:</label>
    <p><select class="form-control" id="id_category" name="category">
      <!-- Populate options dynamically via JavaScript -->
  </select></p>
    <label for="title">Title:</label>
    <p><input class="form-control" type="text" id="titles" name="title"></p>
    <label for="slug">Slug:</label>
    <p><input class="form-control" type="text" id="slugs" name="slug"></p>
    <p><textarea id="descriptions" name="description" rows="3" class="form-control"></textarea></p>
    <label for="embed-code">Embed Code:</label>
<<<<<<< HEAD
    <p><input type="text" id="embed_codes" name="embed_code" class="form-control" > </p>
    <label for="image">Image</label>
    <p><input class="form-control" type="file" id="images" name="image"></p>
    <label for="image-url">Image Url</label>
    <p><input type="text" id="image_url" name="image_url" class="form-control" > </p>
    <label for="git">Git Source Code:</label>
    <p><input type="text" id="git_source_code" name="git_source_code" class="form-control" > </p>
=======
    <p><input type="text" id="embed_codes" name="embed_code" class="form-control"> </p>
    <label for="image-url">Image Url</label>
    <p><input type="text" id="image_url" name="image_url" class="form-control"> </p>
    <label for="image">Website Url</label>
    <p><input class="form-control" type="text" id="website_url" name="website_url"></p>
    <label for="git">Git Source Code:</label>
    <p><input class="form-control" type="text" id="github" name="github"> </p>

>>>>>>> 2619a3918320ef852ef3d49de35081a6e110ccb9
    <p class="d-grid"><button type="submit" class="btn btn-color mt-2">Submit</button></p>
  </form>
 </div>
  
</dialog>

<!-- Close button modal here  -->

dash/templates/dash/port-admin.html
{% extends 'myport/base.html' %}
{% load static %}


{% block content %}
{% if request.user.is_authenticated %}
<div class="row">
  <div class="col-md-3">
    <p>Logged in user: <b>{{ request.user }}</b></p>
  </div>

  <div class="col-md-9">
    <div class="d-flex flex-row-reverse">
      <div ><p style="padding-right: 35px;"><b>Etintech</b></p></div>
    </div>
  </div>
</div>
<hr>

<div class="row">
  <div class="col-md-3">
      <div class="card" style="width: 18rem;">
          <div class="card-header">
            Featured
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><a href="{% url 'dash:dashboard-admin' %}">View Post</a></li>
            <li class="list-group-item" id="open-port-form">Post Portfolio</li>
          </ul>
        </div>

  </div>

  <div class="col-md-9 px-5">
      <div class="port-list">

      </div>

  </div>


</div>
   {% include 'dash/modal.html' %}


{% else %}
  
{% endif %}
  






     
{% endblock content %}
    